# MEDIKANA KNOWLEDGE BASE ENVIRONMENT - CLEAN BUILD
# -------------------------------------------------
# Create and activate:
#   conda env create -f environment.yml
#   conda activate medikana_kb
# Update:
#   conda env update -f environment.yml
# Remove:
#   conda env remove -n medikana_kb

name: medikana_kb
channels:
  - defaults
  - conda-forge
dependencies:
  # Core
  - python=3.10
  - pip
  - numpy=1.26.4
  - packaging<25
  - openpyxl  # Excel reading

  # Install most dependencies from pip for consistency
  - pip:
      # LangChain + Streamlit
      - langchain
      - langchain-community
      - streamlit

      # File parsing
      - pypdf
      - python-docx
      - python-pptx

      # Google API
      - google-api-python-client
      - PyYAML
      - watchdog

      # Vector DB + Embeddings
      - faiss-cpu  # Pip build links to system libomp
      - chromadb   # Vector store
      - sentence-transformers
      - openai

      # Optional tools for later
      - tiktoken